openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
tags:
  - name: admin
    description: Admin API endpoints
  - name: user
    description: API endpoint that pertains to user data
paths:      
  /ping1:
    get:
      tags:
        - user
      operationId: ping1
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong