// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package admin

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// AdminId defines model for adminId.
type AdminId = string

// Id defines model for id.
type Id = string

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /add_admin)
	InsertAdmin(ctx echo.Context) error

	// (POST /auth/login)
	AdminLogin(ctx echo.Context) error

	// (POST /auth/logout)
	AdminLogout(ctx echo.Context) error

	// (GET /users)
	GetUsers(ctx echo.Context) error

	// (GET /users/{id})
	GetUserDetails(ctx echo.Context, id Id) error

	// (PATCH /users/{id}/status)
	GetUserStatus(ctx echo.Context, id Id) error

	// (DELETE /{adminId})
	DeleteAdmin(ctx echo.Context, adminId AdminId) error

	// (GET /{adminId})
	GetAdminDetail(ctx echo.Context, adminId AdminId) error

	// (PUT /{adminId})
	UpdateAdminDetail(ctx echo.Context, adminId AdminId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InsertAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) InsertAdmin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.InsertAdmin(ctx)
	return err
}

// AdminLogin converts echo context to params.
func (w *ServerInterfaceWrapper) AdminLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminLogin(ctx)
	return err
}

// AdminLogout converts echo context to params.
func (w *ServerInterfaceWrapper) AdminLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminLogout(ctx)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsers(ctx)
	return err
}

// GetUserDetails converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserDetails(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserDetails(ctx, id)
	return err
}

// GetUserStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserStatus(ctx, id)
	return err
}

// DeleteAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "adminId" -------------
	var adminId AdminId

	err = runtime.BindStyledParameterWithOptions("simple", "adminId", ctx.Param("adminId"), &adminId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter adminId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAdmin(ctx, adminId)
	return err
}

// GetAdminDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "adminId" -------------
	var adminId AdminId

	err = runtime.BindStyledParameterWithOptions("simple", "adminId", ctx.Param("adminId"), &adminId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter adminId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminDetail(ctx, adminId)
	return err
}

// UpdateAdminDetail converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAdminDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "adminId" -------------
	var adminId AdminId

	err = runtime.BindStyledParameterWithOptions("simple", "adminId", ctx.Param("adminId"), &adminId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter adminId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAdminDetail(ctx, adminId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/add_admin", wrapper.InsertAdmin)
	router.POST(baseURL+"/auth/login", wrapper.AdminLogin)
	router.POST(baseURL+"/auth/logout", wrapper.AdminLogout)
	router.GET(baseURL+"/users", wrapper.GetUsers)
	router.GET(baseURL+"/users/:id", wrapper.GetUserDetails)
	router.PATCH(baseURL+"/users/:id/status", wrapper.GetUserStatus)
	router.DELETE(baseURL+"/:adminId", wrapper.DeleteAdmin)
	router.GET(baseURL+"/:adminId", wrapper.GetAdminDetail)
	router.PUT(baseURL+"/:adminId", wrapper.UpdateAdminDetail)

}
