// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package user

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerUrlOpenAPIEndpointProbably defines the Server URL for OpenAPI endpoint probably
const ServerUrlOpenAPIEndpointProbably = "http://localhost:1323/"

// Id defines model for id.
type Id = string

// UpdateUserDetailJSONBody defines parameters for UpdateUserDetail.
type UpdateUserDetailJSONBody struct {
	Username *string `json:"username,omitempty"`
}

// UpdateUserPreferencesJSONBody defines parameters for UpdateUserPreferences.
type UpdateUserPreferencesJSONBody struct {
	Preference *string `json:"preference,omitempty"`
}

// UpdateUserDetailJSONRequestBody defines body for UpdateUserDetail for application/json ContentType.
type UpdateUserDetailJSONRequestBody UpdateUserDetailJSONBody

// UpdateUserPreferencesJSONRequestBody defines body for UpdateUserPreferences for application/json ContentType.
type UpdateUserPreferencesJSONRequestBody UpdateUserPreferencesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /{id})
	GetUserDetail(ctx echo.Context, id Id) error

	// (PUT /{id})
	UpdateUserDetail(ctx echo.Context, id Id) error

	// (GET /{id}/preferences)
	GetUserPreferences(ctx echo.Context, id Id) error

	// (PUT /{id}/preferences)
	UpdateUserPreferences(ctx echo.Context, id Id) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUserDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserDetail(ctx, id)
	return err
}

// UpdateUserDetail converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserDetail(ctx, id)
	return err
}

// GetUserPreferences converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserPreferences(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserPreferences(ctx, id)
	return err
}

// UpdateUserPreferences converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserPreferences(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserPreferences(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/:id", wrapper.GetUserDetail)
	router.PUT(baseURL+"/:id", wrapper.UpdateUserDetail)
	router.GET(baseURL+"/:id/preferences", wrapper.GetUserPreferences)
	router.PUT(baseURL+"/:id/preferences", wrapper.UpdateUserPreferences)

}
